apiVersion: db.atlasgo.io/v1alpha1
kind: AtlasSchema
metadata:
  name: operational-datastore
spec:
  credentials:
    scheme: postgres
    host: ${STACK_NAME}-rw.postgres.svc
    userFrom:
      secretKeyRef:
        key: user
        name: ${STACK_NAME}-app
    passwordFrom:
      secretKeyRef:
        key: password
        name: ${STACK_NAME}-app
    database: operational_datastore
    port: 5432
  schema:
    sql: |
      create table public.product (
        id int not null generated always as identity,
        name varchar(600) not null,
        primary key (id)
      );

      create table public.feature (
        id int not null generated always as identity,
        name varchar(600) not null,
        primary key (id)
      );

      create table public.product_feature (
        product_id int not null,
        feature_id int not null,
        primary key (product_id, feature_id),
        constraint fk_product foreign key(product_id) references public.product(id),
        constraint fk_feature foreign key(feature_id) references public.feature(id)
      );

      create table public.feature_metric (
        timestamp timestamptz not null,
        start_timestamp timestamptz,
        account_id varchar(255) not null,
        graph_id varchar(255) not null,
        graph_variant varchar(255) not null,
        agent_version varchar(255) not null,
        router_id varchar(255) not null,
        metric_name varchar(255) not null,
        metric_value jsonb null,
        attributes jsonb
      );
